# Site settings
title: "Gabriel Hauber: devBlog"
email: gabriel@ghostdust.com
description: "I develop apps for iOS"
baseurl: ""
url: "http://gabrielhauber.net"
username: GabrielHauber

# Build settings
markdown: kramdown
permalink: /devBlog/:year/:month/:day/:title/
